variable "project_name" {
  description = "Project identifier used as the resource name prefix"
  type        = string
  default     = "mccarthy"
}

variable "storage_prefix" {
  description = "Short token used to build the storage account name (see modules/blob-storage)"
  type        = string
  default     = "mcc"
}

variable "subscription_id" {
  description = "Azure subscription ID"
  type        = string
}

variable "location" {
  description = "Azure region for resources"
  type        = string
  default     = "eastus2"
}

variable "cost_center" {
  description = "CostCenter tag applied to every resource in this stack"
  type        = string
}

# --- Remote state coordinates (shared across stacks) --------------------------

variable "tfstate_resource_group_name" {
  description = "Resource group holding the Terraform state storage account"
  type        = string
  default     = "mccarthy-tfstate-rg"
}

variable "tfstate_storage_account_name" {
  description = "Terraform state storage account name (generated by bootstrap/azure-setup.sh)"
  type        = string
}

variable "tfstate_container_name" {
  description = "Blob container holding Terraform state"
  type        = string
  default     = "tfstate"
}

variable "use_oidc" {
  description = "Authenticate to the state backend with a GitHub OIDC token. True in CI, false for local az-cli-based runs."
  type        = bool
  default     = true
}

variable "use_azuread_auth" {
  description = "Use Entra ID auth against the state storage account instead of shared keys. Requires Storage Blob Data Contributor."
  type        = bool
  default     = true
}

# --- Application ---------------------------------------------------------------

variable "db_admin_username" {
  description = "PostgreSQL administrator username"
  type        = string
  default     = "drupaladmin"
}

variable "db_name" {
  description = "Name of the Drupal database"
  type        = string
  default     = "drupal"
}

variable "developer_identities" {
  description = <<-EOT
    Map of developer username -> AAD object ID. One list of developers, granted
    Storage Blob Data Reader on the drupal-media and db-dumps containers. Both
    grants are container-scoped and read-only, so removing someone from this map
    actually revokes their access.
    Kept out of git (public repo) - set in terraform.tfvars.
  EOT
  type        = map(string)
  default     = {}
}
