variable "project_name" {
  description = "Project identifier used as the resource name prefix"
  type        = string
  default     = "mccarthy"
}

variable "storage_prefix" {
  description = "Short token used to build the storage account name (see modules/blob-storage)"
  type        = string
  default     = "mcc"
}

variable "subscription_id" {
  description = "Azure subscription ID"
  type        = string
}

variable "location" {
  description = "Azure region for resources"
  type        = string
  default     = "eastus2"
}

variable "cost_center" {
  description = "CostCenter tag applied to every resource in this stack"
  type        = string
}

# --- Remote state coordinates (shared across stacks) --------------------------

variable "tfstate_resource_group_name" {
  description = "Resource group holding the Terraform state storage account"
  type        = string
  default     = "mccarthy-tfstate-rg"
}

variable "tfstate_storage_account_name" {
  description = "Terraform state storage account name (generated by bootstrap/azure-setup.sh)"
  type        = string
}

variable "tfstate_container_name" {
  description = "Blob container holding Terraform state"
  type        = string
  default     = "tfstate"
}

variable "use_oidc" {
  description = "Authenticate to the state backend with a GitHub OIDC token. True in CI, false for local az-cli-based runs."
  type        = bool
  default     = true
}

variable "use_azuread_auth" {
  description = "Use Entra ID auth against the state storage account instead of shared keys. Requires Storage Blob Data Contributor."
  type        = bool
  default     = true
}

# --- Image Gallery -------------------------------------------------------------
# The base image and the gallery itself are SHARED with lib-main-infra and owned
# by that repo. Only the app image definition below belongs to this project.
# See README.md > Shared base image.

variable "use_gallery_image" {
  description = "Use image from Azure Compute Gallery (false uses marketplace Rocky Linux)"
  type        = bool
  default     = false
}

variable "gallery_name" {
  description = "Name of the shared Azure Compute Gallery (owned by lib-main-infra)"
  type        = string
  default     = ""
}

variable "gallery_resource_group_name" {
  description = "Resource group containing the shared Azure Compute Gallery (owned by lib-main-infra)"
  type        = string
  default     = ""
}

variable "image_name" {
  description = "Name of this project's app image definition in the shared gallery"
  type        = string
  default     = "mccarthy-rocky-linux-9"
}

variable "image_version" {
  description = "Version of the image to deploy (e.g., 1.0.0)"
  type        = string
  default     = "1.0.0"
}

# Networking
variable "vnet_address_space" {
  description = "Address space for the VNet"
  type        = list(string)
  default     = ["10.0.0.0/16"]
}

variable "web_subnet_prefix" {
  description = "Address prefix for the web subnet"
  type        = string
  default     = "10.0.1.0/24"
}

variable "private_endpoints_prefix" {
  description = "Address prefix for private endpoints subnet"
  type        = string
  default     = "10.0.2.0/24"
}

variable "allowed_ssh_cidr_blocks" {
  description = "CIDR blocks allowed for SSH access"
  type        = list(string)
  default = [
    "160.36.0.0/16",   # UTK campus wired
    "10.65.0.0/16",    # UTK VPN
    "10.46.0.0/15",    # UTK mod1 (10.46.x.x and 10.47.x.x)
    "216.96.128.0/17", # UTK eduroam
    "192.249.1.0/24",  # UTK campus (new range, verify exact CIDR)
  ]
}

# Load Balancer
variable "lb_dns_label" {
  description = "DNS label for Load Balancer public IP (creates <label>.<region>.cloudapp.azure.com)"
  type        = string
  default     = null
}

variable "enable_https" {
  description = "Enable HTTPS on the Load Balancer"
  type        = bool
  default     = false
}

variable "health_probe_path" {
  description = "Path for health probe endpoint"
  type        = string
  default     = "/health"
}

# VM configuration
# Burstable v2 (Basv2). Was Standard_B2s (Bs v1), which Azure has placed under
# capacity growth restrictions from 2026-07-31 and retirement on 2028-07-31.
# Standard_B2als_v2 is the same 2 vCPU / 4 GiB at a slightly lower rate.
# Longer term this moves to a D-class size (Standard_D2as_v5).
variable "vm_size" {
  description = "Size of the VM instances"
  type        = string
  default     = "Standard_B2als_v2"
}

variable "admin_username" {
  description = "Admin username for the VMs"
  type        = string
  default     = "drupaladmin"
}

variable "admin_ssh_public_key" {
  description = "SSH public key for admin access"
  type        = string
}

variable "os_disk_size_gb" {
  description = "Size of the OS disk in GB"
  type        = number
  default     = 64
}

# PostgreSQL configuration
variable "postgresql_sku" {
  description = "SKU for PostgreSQL Flexible Server"
  type        = string
  default     = "B_Standard_B1ms"
}

variable "postgresql_storage_mb" {
  description = "Storage size in MB for PostgreSQL"
  type        = number
  default     = 32768 # 32 GB minimum
}

variable "postgresql_version" {
  description = "PostgreSQL major version"
  type        = string
  default     = "17"
}

variable "db_admin_username" {
  description = "PostgreSQL administrator username"
  type        = string
  default     = "drupaladmin"
}

variable "db_name" {
  description = "Name of the Drupal database"
  type        = string
  default     = "drupal"
}

variable "db_allowed_ips" {
  description = "List of IP addresses allowed to connect to PostgreSQL"
  type        = list(string)
  default     = []
}

# Blob Storage configuration
variable "enable_vmss_blob_access" {
  description = "Enable VMSS blob access role assignment. Set false for initial deployment, true after VMSS exists."
  type        = bool
  default     = false
}

# Drupal configuration
variable "drupal_admin_password" {
  description = "Password for the Drupal admin user"
  type        = string
  sensitive   = true
  default     = null # If not provided, a random password will be generated
}

variable "drupal_site_uuid" {
  description = "Fixed Drupal site UUID for config sync. Must match config/system.site.yml"
  type        = string
  # No default - must be provided for each site to ensure unique UUIDs
}

variable "domain_name" {
  description = "Domain name for TLS certificate (e.g., libdev1.lib.utk.edu)"
  type        = string
  default     = null
}

variable "public_ip_id" {
  description = "Existing Azure public IP resource ID for the Load Balancer. If null, a new IP is created."
  type        = string
  default     = null
}

# --- Media SAS window ----------------------------------------------------------
# Read-only SAS handed to the Apache reverse proxy so it can serve blob media.
# Fixed dates rather than timestamp()/timeadd(), which would reissue the token on
# every plan. Roll media_sas_expiry before it lapses.

variable "media_sas_start" {
  description = "Start of the read-only media SAS validity window (RFC 3339 UTC)"
  type        = string
  default     = "2026-01-01T00:00:00Z"
}

variable "media_sas_expiry" {
  description = "Expiry of the read-only media SAS validity window (RFC 3339 UTC). Media stops being served after this date."
  type        = string
  default     = "2028-01-01T00:00:00Z"
}
