variable "project_name" {
  description = "Project identifier used as the resource name prefix"
  type        = string
  default     = "mccarthy"
}

variable "subscription_id" {
  description = "Azure subscription ID"
  type        = string
}

variable "location" {
  description = "Azure region for resources"
  type        = string
  default     = "eastus2"
}

variable "cost_center" {
  description = "CostCenter tag applied to every resource in this stack"
  type        = string
}

variable "pr_number" {
  description = "Pull request number for ephemeral environments"
  type        = string
  default     = null
}

# --- Remote state coordinates (shared across stacks) --------------------------

variable "tfstate_resource_group_name" {
  description = "Resource group holding the Terraform state storage account"
  type        = string
  default     = "mccarthy-tfstate-rg"
}

variable "tfstate_storage_account_name" {
  description = "Terraform state storage account name (generated by bootstrap/azure-setup.sh)"
  type        = string
}

variable "tfstate_container_name" {
  description = "Blob container holding Terraform state"
  type        = string
  default     = "tfstate"
}

variable "use_oidc" {
  description = "Authenticate to the state backend with a GitHub OIDC token. True in CI, false for local az-cli-based runs."
  type        = bool
  default     = true
}

variable "use_azuread_auth" {
  description = "Use Entra ID auth against the state storage account instead of shared keys. Requires Storage Blob Data Contributor."
  type        = bool
  default     = true
}

# --- Image Gallery -------------------------------------------------------------
# The gallery and the base image are SHARED with lib-main-infra and owned by that
# repo. Only image_name below belongs to this project.

variable "gallery_name" {
  description = "Name of the shared Azure Compute Gallery (owned by lib-main-infra)"
  type        = string
}

variable "gallery_resource_group_name" {
  description = "Resource group containing the shared Azure Compute Gallery (owned by lib-main-infra)"
  type        = string
}

variable "image_name" {
  description = "Name of this project's app image definition in the shared gallery"
  type        = string
  default     = "mccarthy-rocky-linux-9"
}

variable "image_version" {
  description = "Version of the image to deploy"
  type        = string
}

# Networking
variable "subnet_id" {
  description = "ID of the subnet where the VM will be deployed"
  type        = string
}

# VM configuration
variable "vm_size" {
  description = "Size of the VM instance"
  type        = string
  default     = "Standard_D2s_v5"
}

variable "admin_username" {
  description = "Admin username for the VM"
  type        = string
  default     = "drupaladmin"
}

variable "admin_ssh_public_key" {
  description = "SSH public key for admin access"
  type        = string
}

variable "assign_public_ip" {
  description = "Assign a public IP address to the VM for testing access"
  type        = bool
  default     = true
}

# Database configuration (references permanent devtest PostgreSQL)
variable "devtest_db_host" {
  description = "FQDN of the permanent devtest PostgreSQL server"
  type        = string
}

variable "db_admin_username" {
  description = "PostgreSQL administrator username"
  type        = string
  default     = "drupaladmin"
}

variable "db_name" {
  description = "Name of the Drupal database"
  type        = string
  default     = "drupal"
}

# Blob storage configuration (references permanent devtest storage account)
variable "devtest_storage_account" {
  description = "Name of the permanent devtest storage account"
  type        = string
}

# --- Media SAS window ----------------------------------------------------------
# Fixed dates rather than timestamp()/timeadd(), which would reissue the token on
# every plan and replace the VM. Roll media_sas_expiry before it lapses.

variable "media_sas_start" {
  description = "Start of the read-only media SAS validity window (RFC 3339 UTC)"
  type        = string
  default     = "2026-01-01T00:00:00Z"
}

variable "media_sas_expiry" {
  description = "Expiry of the read-only media SAS validity window (RFC 3339 UTC)"
  type        = string
  default     = "2028-01-01T00:00:00Z"
}

